version: '3.5'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    volumes:
      - ${PWD}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - erlang-ekl-network

  kibana:
    build:
      context: .
      dockerfile: kibana-dockerfile
    links:
      - elasticsearch
    volumes:
      - ${PWD}/kibana.yml:/etc/kibana/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - erlang-ekl-network

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    links:
      - elasticsearch
    volumes:
      - ${PWD}/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9125:9125/udp"
    depends_on:
      - elasticsearch
    networks:
      - erlang-ekl-network

networks:
  erlang-ekl-network:
    driver: bridge
    name: erlang-ekl-network
